
services:
  spark-app:
    image: bitnami/spark
    container_name: spark-app
    volumes:
      - ./data:/app/data
      - ./output:/app/output
      - .:/app
    working_dir: /app
    command: >
      bash -c "
      /opt/bitnami/spark/bin/spark-submit 
      --master local[*]
      /app/spark_tfidf.py
      --input /app/data/input.txt
      --min-length 4
      --top-n 10
      "

